apiVersion: apps/v1
kind: Deployment
metadata:
  name: sre-works-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: sre-works-app
  template:
    metadata:
      labels:
        app: sre-works-app
    spec:
      containers:
        - name: sre-works-container
          image: ghcr.io/satoukick/sre-works:main
          ports:
            - containerPort: 8080
